# SUPPORT VECTOR MACHINE

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

supervised classification method that seperates data using hyperplanes

Goal:
used for both classification as well as the regression problems
to create the best line or the decision boundary that can segregate n dimensional space into classes so that we can easily put the new data point in correct category

best decison boundary is hyperplanes

there can be multiple lines / decision boundaries that can seperates n dimensional space

in layman terms , we are separating classes by a line , a line can be drown in diffreent plane , but which one should be there ?

support vectors=> that data points which are on boundary and touching the hyperplane in both +ive and -ive sids,
distance between the support vectors or the margins should be maximum so that both classes can be clearly seperated and 
the new coming data can be easily putted into the required category

dimension of hyperplane depend on feature of dataset means if 2 features then hyperplane will be a staright line.
if 3 features, hyperplane will be 2 dimensional plane.

types:
Linear SVM  -> linearly seperable data, data can be classified by using a single straight line
Non Linear SVM -> for non linearly seperable data, data can't be classified by using staright line, can be calculated as -> z = x^2 + y^2
we can add a third dimensional called z

hyperplane is a line (in 2d space) or a plane that seperates the data points into 2 classes

support vectors are data points which lies nearest to hyperplane, if thses data points changes , the position of hyperplane also changes

w-> . x-> + b = -1 class 2
w-> . x-> + b = 0
w-> . x-> + b = 1 class 1

max = 2 / |w|

works well with smaller datasets
works efficinetly when there is a clear margin of seperation
well with high dimensional data

not suitable for large datasets
no suitable for noiser with overlapping classses

in 3d by using kernal functions

(x1 - x2) = 2 / ||w|| (margin)

maximum margin without overfitting -> soft margin


types of SVM Kernals: 
1. linear
2. polynomial
3. radial basis function (rbf)
4. sigmoid

In [3]:
df = pd.read_csv('wine.csv')
X = df.drop('Wine',axis=1)
y = df['Wine']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
linear_model = SVC(kernel = 'linear')
linear_model.fit(X_train,y_train)
linear_pred = linear_model.predict(X_test)
print('-------Linear SVM--------')
print('Accuracy:',accuracy_score(y_test,linear_pred))
print('\nClassification Report:\n',classification_report(y_test,linear_pred))
print('\nConfusion Matrix:\n',confusion_matrix(y_test,linear_pred))

-------Linear SVM--------
Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00        16
           3       1.00      1.00      1.00        12

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36


Confusion Matrix:
 [[ 8  0  0]
 [ 0 16  0]
 [ 0  0 12]]


In [7]:
rbf_model = SVC(kernel = 'rbf')
rbf_model.fit(X_train,y_train)
rbf_pred = rbf_model.predict(X_test)
print('-------RBF SVM--------')
print('Accuracy:',accuracy_score(y_test,rbf_pred))
print('\nClassification Report:\n',classification_report(y_test,rbf_pred))
print('\nConfusion Matrix:\n',confusion_matrix(y_test,rbf_pred))

-------RBF SVM--------
Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00        16
           3       1.00      1.00      1.00        12

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36


Confusion Matrix:
 [[ 8  0  0]
 [ 0 16  0]
 [ 0  0 12]]


very useful in real world datasets, 
works very well for small datasets
