In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [3]:
df = pd.read_csv("spam.csv",encoding='latin1')
df

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will Ì_ b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [4]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    653  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [5]:
df['spam'] = df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [6]:
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [7]:
X_train,X_test,y_train,y_test = train_test_split(df.Message, df.spam, test_size=0.25)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train_count = cv.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3, 7471))

In [9]:

from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [10]:
X_test_count = cv.transform(X_test.values)
y_pred = model.predict(X_test_count)

print("Accuracy score: ",accuracy_score(y_test,y_pred))
print("Confusion Matrix: \n",confusion_matrix(y_test,y_pred))

Accuracy score:  0.9863603732950467
Confusion Matrix: 
 [[1191    5]
 [  14  183]]


In [11]:
emails = [
    'Hey mohan, can we get together to watch the cricket match tomorrow',
    "upto 20% discount on parking, exclusive offer is going on, don't miss that reward!"
]
email_count = cv.transform(emails)
model.predict(email_count)

array([0, 0])

In [12]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.9863603732950467

In [25]:
from sklearn.datasets import load_wine
df = load_wine()

X = df.data
y = df.target
target_name = df.target_names
print(target_name)
print('\n')
print(X)
print('\n')
print(y)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
print('\n')
print(len(X_train))

print(len(X_test))

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train)
y_pred = nb.predict(X_test)
acc_gnb = accuracy_score(y_test,y_pred)
print("Accuracy: ",acc_gnb)
print("Classification Report: \n",classification_report(y_test,y_pred))
print("Actual values: ",y_test[:5])
print("Predicted values: ",y_pred[:5])
print('\n Multinomial Naive Bayes workflow is: \n')
X_tr,X_ts,y_tr,y_ts = train_test_split(X,y,test_size=0.3,random_state=0)
ms = MinMaxScaler()

X_tr = ms.fit_transform(X_tr)
X_ts = ms.transform(X_ts)

model = MultinomialNB()
model.fit(X_tr,y_tr)
y_pre_ms = model.predict(X_ts)
acc_mnb = accuracy_score(y_ts,y_pre_ms)
print("Accuracy score: ",acc_mnb)
print("Classification report: \n",classification_report(y_ts,y_pre_ms))
print("Actual values: ",y_ts[:5])
print("Predicted values: ",y_pre_ms[:5])

if acc_gnb > acc_mnb:
    best_mdl = nb
    best_accuracy = acc_gnb
    model_name = "Gaussian Naive Bayes"
else:
    best_mdl = mnb
    best_accuracy = acc_mnb
    model_name = "Multinomial Naive Bayes"

print(f"The best model for the wine dataset is: {model_name} with accuracy: {best_accuracy:.4f}")

['class_0' 'class_1' 'class_2']


[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


124
54
Accuracy:  0.9444444444444444
Classification Report: 
               precision    recall  f1-score   support

           0       0.90      1.00      0.95        19
           1       1.